# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usr_id',
        ),
    ]
