"""
Django settings for djangoapp project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from ctypes import *



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'w4zyq4=e=@3vp!t!+i$q_mxl7@&b!-0lu4m^4k@u04$lwz7w#)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ajax_forms',
    'webapp',
    'widget_tweaks',
	'sslserver',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangoapp.urls'

APPLICATION_NAME = 'webapp'
APPLICATION_PATH = os.path.join(BASE_DIR, APPLICATION_NAME)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(APPLICATION_PATH, 'templates/static')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [ APPLICATION_PATH + '/templates/static/' ]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)


LOGIN_REDIRECT_URL = '/wizard'

LOGIN_URL = '/login'

MEDIA_ROOT = 'D:\\tmp'

TEMP_FOLDER_NAME = 'D:\\tmp\\'

XSD_FILE_PATH = str(STATICFILES_DIRS[0]) + "xsd\\onecell-config.xsd"

XML_ERROR_SYNTAX_LOG_PATH = "C:\\Users\\pkulai\\Desktop\\error_xml.log"

XML_ERROR_SCHEMA_LOG_PATH = "C:\\Users\\pkulai\\Desktop\\error_schema.log"

SAMPLE_CSV_TEMPLATE_PATH = str(STATICFILES_DIRS[0]) + "xsd\\onecell-config-sample.xml"

SHARED_LIBRARY_PATH = "/conf_files/pkulai/web_test.so"

webapi = 0
# webapi = CDLL(SHARED_LIBRARY_PATH)
# webapi.webgui_initialize()


WHITELIST_PERSISTENCE_FILE = "/conf_files/ruWhitelist"
OPERATOR_CONFIG_FOLDER = "/conf_files/operator_config/"
HEMSURL_PERSISTENCE_FILE = "hemsUrl"
HEMSACCESS_PERSISTENCE_FILE = "HeMSAccess"
CA_SERVER_PERSISTENCE_FILE = "CMPv2Cfg"
SECGW1_PERSISTENCE_FILE = "gatewayUrl"
SECGW2_PERSISTENCE_FILE = "gatewayUrl2"
TIMING_SOURCE_PERSISTENCE_FILE = "ptpmode"
STATICTIACFG1_PERSISTENCE_FILE = "StaticTIACfg"
STATICTIACFG2_PERSISTENCE_FILE = "StaticTIACfg2"
PORTCONFIG_PERSISTENCE_FILE = "/conf_files/WebGUI/portConfig.cfg"
